# Generated by Django 3.2.6 on 2021-08-09 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0003_auto_20210809_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyer',
            name='id',
        ),
        migrations.AlterField(
            model_name='surveyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
