# Generated by Django 3.2.6 on 2021-08-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0004_auto_20210809_2230"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="asker",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.surveyer",
            ),
            preserve_default=False,
        ),
    ]
