# Generated by Django 3.2.6 on 2021-08-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_analysis_asker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='userstot',
            field=models.IntegerField(null=True),
        ),
    ]
