# Generated by Django 3.2.6 on 2021-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0012_alter_analysis_userstot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="ans1count",
            field=models.IntegerField(null=True),
        ),
    ]
