# Generated by Django 3.2.6 on 2021-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0014_auto_20210816_1401"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="ans1count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="ans2count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="ans3count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="ans4count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="ans5count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="ans6count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="analysis",
            name="userstot",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
